In [2]:
import sys
sys.path.append('pmi_accuracy')
import txt_to_pmi

In [3]:
import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', DEVICE)
if DEVICE.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:',
            round(torch.cuda.memory_allocated(0)/1024**3, 1), 'GB')
    print('Cached:   ',
            round(torch.cuda.memory_reserved(0)/1024**3, 1), 'GB')
    print()

MODEL = txt_to_pmi.languagemodel.BERT(
    DEVICE, 'bert-base-cased', 32)

Using device: cuda
Quadro RTX 8000
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB



Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).



Language model 'bert-base-cased' (with batchsize = 32) initialized on cuda.



In [7]:
example_file = [
    "Solo woodwind players have to be creative if they want to work a lot",
    "The oboist Heinz Holliger has taken a hard line about the problem: He commissions and splendidly interprets fearsome contemporary scores and does some conducting, so he doesn't have to play the same Mozart and Strauss concertos over and over again.", 
    "Richard Stoltzman has taken a gentler, more audience-friendly approach."]
sentences = [line.strip().split(' ') for line in example_file]

outs = txt_to_pmi.get_cpmi(MODEL, sentences, verbose=True)

  0%|          | 0/3 [00:00<?, ?it/s]


sentence 0: ['Solo', 'woodwind', 'players', 'have', 'to', 'be', 'creative', 'if', 'they', 'want', 'to', 'work', 'a', 'lot']

• Token list:     ['Solo', 'woodwind', 'players', 'have', 'to', 'be', 'creative', 'if', 'they', 'want', 'to', 'work', 'a', 'lot']
• Subword tokens: ['Solo', 'wood', '##wind', 'players', 'have', 'to', 'be', 'creative', 'if', 'they', 'want', 'to', 'work', 'a', 'lot']
• tok->span:      [(0,), (1, 2), (3,), (4,), (5,), (6,), (7,), (8,), (9,), (10,), (11,), (12,), (13,), (14,)]
• span->tok:      {(0,): 0, (1, 2): 1, (3,): 2, (4,): 3, (5,): 4, (6,): 5, (7,): 6, (8,): 7, (9,): 8, (10,): 9, (11,): 10, (12,): 11, (13,): 12, (14,): 13}
• padleft:        [101]
• padright:       [102]
• input_ids:      [101, 11977, 3591, 11129, 2139, 1138, 1106, 1129, 6228, 1191, 1152, 1328, 1106, 1250, 170, 1974, 102]



 33%|███▎      | 1/3 [00:00<00:00,  6.64it/s]                          


• pseudo_loglik: -39.27373409352731
• cpmi matrix:
[[ 0.00e+00  3.24e+00  1.79e+00 -3.16e-01 -1.35e-01 -5.19e-02  5.06e-01
   1.25e+00  1.32e-01 -2.27e-01  7.98e-02  9.18e-02  1.65e-01  3.31e-01]
 [ 1.27e+00  0.00e+00  8.03e+00  1.11e+00 -6.23e-01  1.94e-01  5.65e-01
  -1.12e-01 -4.94e-01 -5.49e-01 -3.01e-01  8.03e-01 -1.36e-01 -5.24e-01]
 [-3.51e-01  6.36e+00  0.00e+00 -3.53e-02  7.17e-02 -1.43e-01  5.33e-01
   8.30e-02  7.15e-01  8.18e-02  4.06e-02  1.19e-01  4.45e-02  1.06e-01]
 [-9.15e-02  1.21e-01 -7.79e-01  0.00e+00  1.41e+00  4.30e-01  1.00e-01
   4.35e-01  1.69e-01  1.04e-01 -1.02e-01 -2.50e-01 -1.76e-01 -1.83e-01]
 [ 1.02e-03  2.62e-04 -9.70e-05  8.12e-01  0.00e+00  1.78e+00  1.27e-04
   6.79e-04  1.79e-04 -5.24e-06  1.25e-05  9.34e-05  4.91e-05  8.71e-05]
 [-5.05e-03  8.58e-02 -3.92e-02  9.71e-02  4.64e+00  0.00e+00  2.63e+00
  -1.58e-02 -5.85e-03 -1.60e-02  3.57e-03  4.48e-02 -3.52e-03 -4.28e-02]
 [-6.38e-02  4.49e-01  5.64e-01  4.73e-02  2.76e-01  4.48e+00  0.00e+00
  -1.3


 67%|██████▋   | 2/3 [00:02<00:01,  1.71s/it]                            


• pseudo_loglik: -146.44325935254756
• cpmi matrix:
[[ 0.00e+00  5.97e-01  6.41e-03 ...  3.72e-02  2.45e-02  8.16e-02]
 [ 7.36e+00  0.00e+00 -2.47e+00 ...  1.02e-01  1.61e-01  3.35e-01]
 [ 9.62e-01  8.14e-01  0.00e+00 ...  1.29e-01  9.40e-02  1.62e-01]
 ...
 [ 7.86e-06  3.81e-06 -1.20e-05 ...  0.00e+00  3.50e+00  1.63e-03]
 [-9.65e-06 -2.95e-05 -3.11e-05 ...  7.17e+00  0.00e+00  1.03e-03]
 [ 1.56e-03  7.56e-04  1.80e-03 ...  8.24e-01  8.90e+00  0.00e+00]]

sentence 2: ['Richard', 'Stoltzman', 'has', 'taken', 'a', 'gentler,', 'more', 'audience-friendly', 'approach.']

• Token list:     ['Richard', 'Stoltzman', 'has', 'taken', 'a', 'gentler,', 'more', 'audience-friendly', 'approach.']
• Subword tokens: ['Richard', 'St', '##olt', '##zman', 'has', 'taken', 'a', 'gentle', '##r', ',', 'more', 'audience', '-', 'friendly', 'approach', '.']
• tok->span:      [(0,), (1, 2, 3), (4,), (5,), (6,), (7, 8, 9), (10,), (11, 12, 13), (14, 15)]
• span->tok:      {(0,): 0, (1, 2, 3): 1, (4,): 2, (5,): 3,


bert-base-cased: batches:   0%|          | 0/5 [00:00<?, ?it/s]
                                                               


• pseudo_loglik: -42.45163962407969
• cpmi matrix:
[[ 0.00e+00  3.32e+00  8.61e-02 -7.48e-02  3.04e-02  2.95e-02 -3.34e-02
  -2.34e-01  2.71e-01]
 [ 4.29e+00  0.00e+00  5.02e+00  2.98e-01  1.46e-02  5.82e-01 -3.03e-02
   4.69e-01  5.49e-01]
 [-9.37e-02  2.57e+00  0.00e+00  3.45e+00 -1.37e-01 -1.80e-01 -4.54e-02
   7.90e-02  2.48e-01]
 [-9.41e-02  8.65e-02  5.60e+00  0.00e+00  6.60e+00 -3.27e-01  1.74e-01
  -7.13e-01  1.59e+00]
 [ 9.93e-04  1.54e-03  5.30e-03  2.50e-03  0.00e+00  2.82e+00  6.66e-04
   2.80e-03  6.23e-02]
 [ 2.36e-01  7.28e-01  5.82e-02 -6.69e-02  6.59e+00  0.00e+00  1.26e-01
   9.58e-03 -1.04e+00]
 [-1.18e-02  7.40e-03  1.65e-03 -5.49e-03  2.07e-02  5.00e+00  0.00e+00
   9.42e-01 -8.80e-03]
 [-3.89e-01 -6.84e-02  9.72e-02  3.53e-02 -4.12e-01  7.64e-01  2.89e+00
   0.00e+00  7.77e-01]
 [ 9.76e-03  8.57e-02  1.63e-01  2.00e+00 -2.74e-03  3.94e+00  1.15e-03
   7.23e-02  0.00e+00]]

----------
CPMI matrix value at position [i,j] is
 pmi(w_i, w_j | c) = log p(w_i | c) - log