In [2]:
import sys
sys.path.append('pmi_accuracy')
import txt_to_pmi

In [3]:
import torch

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', DEVICE)
if DEVICE.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:',
            round(torch.cuda.memory_allocated(0)/1024**3, 1), 'GB')
    print('Cached:   ',
            round(torch.cuda.memory_reserved(0)/1024**3, 1), 'GB')
    print()

MODEL = txt_to_pmi.languagemodel.BERT(
    DEVICE, 'bert-base-cased', 32)

Using device: cuda
Quadro RTX 8000
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB



Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).



Language model 'bert-base-cased' (with batchsize = 32) initialized on cuda.



In [4]:
file = ["Here is an exemplary sentence.", "This one follows."]
sentences = [line.strip().split(' ')
                     for line in file]

outs = txt_to_pmi.get_cpmi(MODEL, sentences, verbose=True)

  0%|          | 0/2 [00:00<?, ?it/s]


sentence 0: ['Here', 'is', 'an', 'exemplary', 'sentence.']

• Token list:     ['Here', 'is', 'an', 'exemplary', 'sentence.']
• Subword tokens: ['Here', 'is', 'an', 'ex', '##em', '##p', '##lary', 'sentence', '.']
• tok->span:      [(0,), (1,), (2,), (3, 4, 5, 6), (7, 8)]
• span->tok:      {(0,): 0, (1,): 1, (2,): 2, (3, 4, 5, 6): 3, (7, 8): 4}
• padleft:        [101]
• padright:       [102]
• input_ids:      [101, 3446, 1110, 1126, 4252, 5521, 1643, 18480, 5650, 119, 102]



 50%|█████     | 1/2 [00:01<00:01,  1.89s/it]                          


• pseudo_loglik: -31.351733036339283
• cpmi matrix:
[[ 0.00  1.05 -0.85  3.62 -0.90]
 [ 0.54  0.00  0.14  0.08  0.22]
 [-0.53  0.28  0.00  4.01  0.09]
 [-0.22 -1.42  0.83  0.00 -1.52]
 [ 2.45  0.68  0.46  3.81  0.00]]

sentence 1: ['This', 'one', 'follows.']

• Token list:     ['This', 'one', 'follows.']
• Subword tokens: ['This', 'one', 'follows', '.']
• tok->span:      [(0,), (1,), (2, 3)]
• span->tok:      {(0,): 0, (1,): 1, (2, 3): 2}
• padleft:        [101]
• padright:       [102]
• input_ids:      [101, 1188, 1141, 3226, 119, 102]



bert-base-cased: batches:   0%|          | 0/1 [00:00<?, ?it/s]
                                                               


• pseudo_loglik: -14.565191261470318
• cpmi matrix:
[[ 0.00  1.78  2.54]
 [-1.32  0.00 -0.90]
 [-0.01 -1.22  0.00]]

----------
CPMI matrix value at position [i,j] is
 pmi(w_i, w_j | c) = log p(w_i | c) - log p(w_i | c without w_j)
 where w_i is ith word in sentence, and c is rest of sentence.
----------
